### ISSUE TITLE
Preprocessing  dataset

### ISSUE THREAD

**Issue by yongwuML** [zhengyuf/STED-gaze#1]
Could you upload the code of  pre-process datasets to full-image

**Comment by zhengyuf** [comment]
Hey Yong,
We use the exact same data per-processing pipeline as [FAZE](https://github.com/NVlabs/few_shot_gaze).
Please check [this repository](https://github.com/swook/faze_preprocess) for more details :)

**Comment by yongwuML** [comment]
@zhengyuf , thank you very much.
