### ISSUE TITLE
Gettng  high gaze_redirection loss 

### ISSUE THREAD

**Issue by codeastra2** [zhengyuf/STED-gaze#11]
Hello ,
First of all thanks so much for your excellent work! 
I am running the pipeline you have provided to get similiar results.
I ran the data preprocessing file for both MPIIGaze and Gazecapture to get the results. 
I am getting a training loss of 4.3 degree, whereas the testing error is nearly 17.2 degrees, this is on GazeCapture. 
Please find both the charts [here](https://drive.google.com/drive/folders/1OT1ZFcL8IjkMYzr3Qo9oTgxCbCseuVLw?usp=sharing).
This was after running the training on GC completely. I however did not run the semi supervised version of it, but have triggered a run of this and will update the results here. Could you please let me know what could be the reasons for the high error?

The table of reference would be table 2, with the errors on GC being 2.195. 
Thanks in advance!

**Comment by zhengyuf** [comment]
Hi,

I'm afraid that I don't know the exact reason for this.
Have you checked the gaze-redirected images? Do they look reasonable?

Yufeng

**Comment by xjjww** [comment]
Hi, I am trying to train STED following the README instructions.  But I found that https://github.com/swook/faze_preprocess doesn't provide preprocessings of 'columbia' or 'eyediap' datasets, which are needed by the evaluation of STED.  Specifically, respective supplement data are needed during preprocessing, which I don't know how to acquire.
Could you tell me where to get the supplement data, or how to generate them？
Looking forward to your reply. Thank you!
