### ISSUE TITLE
How to run with pre-trained model?

### ISSUE THREAD

**Issue by huytuong010101** [zhengyuf/STED-gaze#12]
**Thank u for perfect repository <3**
I see that you shared your pre-trained model but I don't know how to run the source code with your pre-trained model 
Can you help me?

**Comment by zhengyuf** [comment]
Hi,

The source code contains the code for loading pre-trained models.
You can set config.save_path and config.load_step to specific the repository and name for the checkpoints.
Also, please see line 131 from train_st_ed.py for details.

Yufeng
