### ISSUE TITLE
Can I get 'PerceptualSimilarity' file?

### ISSUE THREAD

**Issue by san9569** [zhengyuf/STED-gaze#2]
Hi

I want to execute `train_st_ed.py`, but I faced `ModuleNotFoundError` below.

![image](https://user-images.githubusercontent.com/60248657/99520368-5a521100-29d6-11eb-85b2-a2cc45c3ef9f.png)

Can I get a model of `PerceptualSimilarity`?

**Comment by zhengyuf** [comment]
Hey, 

Could you check [this repo](https://github.com/richzhang/PerceptualSimilarity)?
