### ISSUE TITLE
suplementary files

### ISSUE THREAD

**Issue by yongwuML** [zhengyuf/STED-gaze#3]
@zhengyuf 
Hi, I am Yong.
I am very sorry to bother you, could you upload the EYEDIAP_supplementary.h5 and Columbia_supplementary.h5 for pre-processing dataset. I have downloaded the MPIIFaceGaze_supplementary.h5 and GazeCapture_supplementary.h5
 from FAZE.
Thank you.

**Comment by zhengyuf** [comment]
Hey Yong,
We don't have the files ready for eyediap and columbia at the moment, I will inform you when we upload them.
But notice that we don't train with these files, the only file used for training is GazeCapture.

**Comment by yongwuML** [comment]
@zhengyuf ,
OK, thank you.
Please let me know when you upload them. Thank you again.

**Comment by yongwuML** [comment]
@zhengyuf 
Hi, Zhengyu, 
I am sorry to bother you. I know you are very busy, so  I just want to know how can I get the Distortion Coefficients for eyediap? 
If you upload the  EYEDIAP_supplementary.h5 and Columbia_supplementary.h5, that will be great.  Thank you.

**Comment by zhengyuf** [comment]
https://github.com/hysts/pytorch_mpiigaze_demo/issues/3
