### ISSUE TITLE
problem when running your train/eval scripts

### ISSUE THREAD

**Issue by AlmogDavid** [zhengyuf/STED-gaze#4]
Hi, first of all thanks for sharing the code, the project looks very cool.
When I try to run your scripts (according to the readme) I get this error:
ModuleNotFoundError: No module named 'models.PerceptualSimilarity'

How can I solve it?

**Comment by zhengyuf** [comment]
Could you please check this out? #2 
I'll update the codes when i have time to make it easier to run, sorry for the inconvenience.
