### ISSUE TITLE
There appears to be a few errors in the names of some items from eval.json

### ISSUE THREAD

**Issue by LeArmadillo** [zhengyuf/STED-gaze#6]
There appears to be a few errors in the names of some items from eval.json, they currently read:
    "size_0d_unit": 1024,
    "num_1d_units": 4,
    "size_1d_unnit": 16,
    "num_2d_uits": 4,
    "size_2d_unit": 16,
should they read as follows?:
    "size_0d_unit": 1024,
    "num_1d_units": 4,
    "size_1d_unit": 16,
    "num_2d_units": 4,
    "size_2d_unit": 16,

**Comment by zhengyuf** [comment]
Hey, thank you for spotting this typo, it's corrected now :)
