### ISSUE TITLE
Encoder weights not saved

### ISSUE THREAD

**Issue by LeArmadillo** [zhengyuf/STED-gaze#7]
It appears the model trained by the ST-ED.json isn't saving the encoder weights properly when run by the eval.json.  Can you advise a fix to this issue?  

# python train_st_ed.py config/eval.json
config/eval.json
2021-01-28 11:48:38,787 Loading config/eval.json
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
Loading model from: /root/miniconda3/lib/python3.8/site-packages/lpips/weights/v0.1/alex.pth
Traceback (most recent call last):
  File "train_st_ed.py", line 48, in <module>
    load_model(network, "models/"+ str(config.load_step) + '.pt')
  File "/translation/STED-gaze-master/utils.py", line 250, in load_model
    network.encoder.load_state_dict(checkpoint['encoder'])
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Encoder:
        Missing key(s) in state_dict: "encoder.initial.conv1.weight", "encoder.initial.conv2.weight", "encoder.block1.compo1.conv.weight", "encoder.block1.compo2.conv.weight", "encoder.block1.compo3.conv.weight", "encoder.block1.compo4.conv.weight", "encoder.trans1.composite.conv.weight", "encoder.block2.compo1.conv.weight", "encoder.block2.compo2.conv.weight", "encoder.block2.compo3.conv.weight", "encoder.block2.compo4.conv.weight", "encoder.trans2.composite.conv.weight", "encoder.block3.compo1.conv.weight", "encoder.block3.compo2.conv.weight", "encoder.block3.compo3.conv.weight", "encoder.block3.compo4.conv.weight", "encoder.trans3.composite.conv.weight", "encoder.block4.compo1.conv.weight", "encoder.block4.compo2.conv.weight", "encoder.block4.compo3.conv.weight", "encoder.block4.compo4.conv.weight", "encoder.trans4.composite.conv.weight", "encoder.block5.compo1.conv.weight", "encoder.block5.compo2.conv.weight", "encoder.block5.compo3.conv.weight", "encoder.block5.compo4.conv.weight", "encoder_fc_pseudo_labels1.weight", "encoder_fc_pseudo_labels1.bias", "encoder_fc_pseudo_labels2.weight", "encoder_fc_pseudo_labels2.bias", "encoder_fc_embeddings1.weight", "encoder_fc_embeddings1.bias", "encoder_fc_embeddings2.weight", "encoder_fc_embeddings2.bias".
        Unexpected key(s) in state_dict: "module.encoder.initial.conv1.weight", "module.encoder.initial.conv2.weight", "module.encoder.block1.compo1.conv.weight", "module.encoder.block1.compo2.conv.weight", "module.encoder.block1.compo3.conv.weight", "module.encoder.block1.compo4.conv.weight", "module.encoder.trans1.composite.conv.weight", "module.encoder.block2.compo1.conv.weight", "module.encoder.block2.compo2.conv.weight", "module.encoder.block2.compo3.conv.weight", "module.encoder.block2.compo4.conv.weight", "module.encoder.trans2.composite.conv.weight", "module.encoder.block3.compo1.conv.weight", "module.encoder.block3.compo2.conv.weight", "module.encoder.block3.compo3.conv.weight", "module.encoder.block3.compo4.conv.weight", "module.encoder.trans3.composite.conv.weight", "module.encoder.block4.compo1.conv.weight", "module.encoder.block4.compo2.conv.weight", "module.encoder.block4.compo3.conv.weight", "module.encoder.block4.compo4.conv.weight", "module.encoder.trans4.composite.conv.weight", "module.encoder.block5.compo1.conv.weight", "module.encoder.block5.compo2.conv.weight", "module.encoder.block5.compo3.conv.weight", "module.encoder.block5.compo4.conv.weight", "module.encoder_fc_pseudo_labels1.weight", "module.encoder_fc_pseudo_labels1.bias", "module.encoder_fc_pseudo_labels2.weight", "module.encoder_fc_pseudo_labels2.bias", "module.encoder_fc_embeddings1.weight", "module.encoder_fc_embeddings1.bias", "module.encoder_fc_embeddings2.weight", "module.encoder_fc_embeddings2.bias".

**Comment by zhengyuf** [comment]
check this out: https://github.com/NVlabs/few_shot_gaze/issues/19
are you using multi-gpu training?

**Comment by LeArmadillo** [comment]
yes

**Comment by LeArmadillo** [comment]
I managed to fix it by adjusting the load_model function in util.py to remove the "module" word from the keys, you'll need to do something similar for the decoder and discriminator: 

    if next(iter(checkpoint['encoder'].keys())).startswith('module.'):
        checkpoint['encoder'] = dict([(k[7:], v) for k, v in checkpoint['encoder'].items()])

**Comment by zhengyuf** [comment]
Hey,
the provided model checkpoint is trained with single gpu, I just tested eval.py with both single and multi gpu training, and i had no problem loading the problem with either case.
Maybe if someone else meets the same problem as you, they can consider to remove 'module' as you did.
